workflows:
  version: 2

  build:
    name: Build
    script:
      - echo "Installing dependencies"
      - ./gradlew dependencies

      - echo "Building the release app"
      - ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

