workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        scripts:
            - ls -l "$FCI_BUILD_DIR"
            - chmod +x "$FCI_BUILD_DIR/gradlew"
            - "$FCI_BUILD_DIR/gradlew assembleRelease"
        artifacts:
            - build/outputs/**/**/*.apk
