workflows:
release-workflow:
  name: Native Android
  max_build_duration: 60
  environment:
  scripts:
    - |
      # Decrypt and set up keystore
      echo $CM_KEYSTORE | base64 --decode > "$FCI_BUILD_DIR/testingkey.jks"
      cat >> "$FCI_BUILD_DIR/keystore.properties" <<EOF
      storePassword=android
      keyPassword=android
      keyAlias=codemagic
      storeFile=testingkey.jks
      EOF
      
      # Build the release APK
      ./gradlew assembleRelease
  artifacts:
    - app/build/**/outputs/**/*.apk
