# Workflow setup for building Native Android project
workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        scripts:
            - chmod +x gradlew assembleRelease
        artifacts:
            - build/outputs/**/**/*.apk

